name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run:    
    runs-on: ${{ matrix.operating-system }}
    strategy:      
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']
        phpunit: [7.5.15]
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    
    services:
      mysql:
        image: mysql:5.7.27
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main

    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: elliotcondon/acf
        path: advanced-custom-fields-pro
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-versions }}
        extension-csv: mbstring, intl #optional, setup extensions
        ini-values-csv: post_max_size=256M, short_open_tag=On #optional, setup php.ini configuration
        coverage: xdebug #optional, setup coverage driver
        pecl: false #optional, setup PECL

    - name: Composer install
      run: composer install --optimize-autoloader --prefer-dist
      
    - name: Install PHPUnit
      run: composer global require "phpunit/phpunit=${{ matrix.phpunit }}"
      
    - name: Install WP Tests
      run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:33306 latest
      
    - name: PHPUnit tests
      run: phpunit

    - name: list dir
      run: ls -la  
